[package]
name = "blockishfire"
version = "0.2.0"
authors = ["yazgoo <yazgoo@gmail.com>"]
description = "doomfire in the terminal"
edition = "2018"
license = "MIT"

[dependencies]
crossterm = "0.15"
blockish = "0.0.8"
rand = "0.7"
